### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by owikle** [thecdil/mancini_source#1]
- [x] - Toggle between letter versions
- [x] - Use includes and csv for tooltip data?
- [x] - Appendix with all names/places (link to see list of letters where all appear?)
- [x] - Letter text and image side by side?
- [x] - Nav, index, and letters pages

**Comment by owikle** [comment]
- [x] Have dates link to timeline
